# Generated by Django 5.1.6 on 2025-02-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categoria'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(blank='false', max_length=200, null='false', verbose_name='categoria do produto'),
        ),
    ]
