# Generated by Django 5.1.6 on 2025-02-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_categoria_options_alter_categoria_nome'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='Categoria',
        ),
    ]
