# Generated by Django 5.1.6 on 2025-02-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_categoria_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank='false', max_length=200, null='false', verbose_name='Categorias do produto')),
            ],
            options={
                'verbose_name': 'Categorias',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categorias',
            },
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
